# Generated by Django 5.0 on 2024-01-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_member1_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member1',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='member_photo/'),
        ),
    ]
