# Generated by Django 5.0 on 2024-01-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_member1_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member1',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
